## Introduction to Tensors

In [2]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [6]:
# Creating tensors with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
# Check no. of dimensions of a tensor
scalar.ndim

0

In [11]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [12]:
# Check dimensions of vector
vector.ndim

1

In [14]:
# Create a matrix 
matrix = tf.constant([[7,10],[10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7]])>

In [15]:
# check matrix dimensions
matrix.ndim

2

In [22]:
# matrix
m2 = tf.constant([[10., 7.], [9.,10.], [7.,10.]], dtype=tf.float16)
m2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 9., 10.],
       [ 7., 10.]], dtype=float16)>

In [23]:
# dimension of m2
m2.ndim

2

In [30]:
m3 = tf.constant([[[1,2,3],
                  [4,5,6]],
                  [[7,8,9],
                  [10,11,12]],
                 [[13,14,15],
                 [16,17,18]]], dtype=tf.int16)
m3

<tf.Tensor: shape=(3, 2, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int16)>

In [26]:
m3.ndim

3

## Creating tensors with tf.Variable

In [36]:
var = tf.Variable
var

tensorflow.python.ops.variables.Variable

In [37]:
var = tf.Variable([[1,2],[3,4]])
var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [47]:
var.assign([[1,2],[10,7]])
var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 1,  2],
       [10,  7]])>

In [62]:
var[0].assign([4,5])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[ 4,  5],
       [10,  7]])>

## Creating random tensors

In [67]:
tf.random.uniform(shape=(3,2,2))

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[0.74659383, 0.0404588 ],
        [0.44859898, 0.5106667 ]],

       [[0.8429239 , 0.17487144],
        [0.87220395, 0.32960153]],

       [[0.16648912, 0.0104022 ],
        [0.0621835 , 0.02846444]]], dtype=float32)>

In [74]:
rand = tf.random.Generator.from_seed(42)
rand = rand.normal(shape=(2,2))
rand

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

## shuffle order of elements in tensor

In [75]:
not_shuffled = tf.constant([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [106]:
tf.random.set_seed(42) # global seed, same order shuffled
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])>

## numpy tensors

In [107]:
tf.ones([4,4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [112]:
tf.zeros(shape=(4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

#### numpy and tf arrays are similar mostly. tf arrays can be run on gpu

In [113]:
import numpy as np
numpy_a = np.arange(1,25, dtype=np.int32)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [117]:
tf.constant(numpy_a,shape=(3,2,4))

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])>

#### important attributes
###### shape, Rank, Axis or dimensions, size

In [119]:
rank4tensor = tf.zeros(shape=(2,3,4,5))
rank4tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [134]:
rank4tensor.shape, rank4tensor.ndim, tf.size(rank4tensor), rank4tensor.dtype, rank4tensor.shape[0], \
rank4tensor.shape[-1], tf.size(rank4tensor).numpy()

(TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>,
 tf.float32,
 2,
 5,
 120)

### indexing tensors

In [144]:
rank4tensor[:1,:,:,:4]

<tf.Tensor: shape=(1, 3, 4, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [147]:
rank2tensor = tf.constant([[10,7],[1,2]])
rank2tensor.shape, rank2tensor.ndim, rank2tensor

(TensorShape([2, 2]),
 2,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 1,  2]])>)

In [158]:
rank3tensor = rank2tensor[..., tf.newaxis]
rank3tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 1],
        [ 2]]])>

In [166]:
# expand axis
tf.expand_dims(rank2tensor,axis=2)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 1],
        [ 2]]])>

## operators

In [169]:
x = tf.constant([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
x + 10, x * 10, x - 5, x / 4

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[-4, -3, -2],
        [-1,  0,  1],
        [ 2,  3,  4]])>,
 <tf.Tensor: shape=(3, 3), dtype=float64, numpy=
 array([[0.25, 0.5 , 0.75],
        [1.  , 1.25, 1.5 ],
        [1.75, 2.  , 2.25]])>)

In [171]:
tf.add(x,10), tf.subtract(x ,5) , tf.multiply(x,10), tf.divide(x,4)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[-4, -3, -2],
        [-1,  0,  1],
        [ 2,  3,  4]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])>,
 <tf.Tensor: shape=(3, 3), dtype=float64, numpy=
 array([[0.25, 0.5 , 0.75],
        [1.  , 1.25, 1.5 ],
        [1.75, 2.  , 2.25]])>)

## matmul

In [173]:
tf.matmul(tf.add(x,10),tf.subtract(x ,5) )

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-30,   6,  42],
       [-39,   6,  51],
       [-48,   6,  60]])>